apiVersion: v1
kind: Service
metadata:
  name: hello-api
  namespace: hello
  labels:
    app: hello-api
spec:
  type: ClusterIP
  selector:
    app: hello-api
  ports:
    - port: 80
      targetPort: 8080   # Spring Boot port
      protocol: TCP
