apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  namespace: gateway
  annotations:
    kubernetes.io/ingress.class: alb

    # Enable HTTP + HTTPS listeners on ALB
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'

    # Redirect all HTTP traffic to HTTPS automatically
    alb.ingress.kubernetes.io/ssl-redirect: "443"

    # Attach your ACM certificate
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:121897425968:certificate/765872ed-1967-455b-a916-462c19cf6675

    # Internet-facing load balancer
    alb.ingress.kubernetes.io/scheme: internet-facing

spec:
  rules:
    - host: api.couplemeant.com
      http:
        paths:
          - path: /gateway
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
